// import "./globals.css";
import Link from 'next/link';
import { Lora } from 'next/font/google'
 
const lora = Lora({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
 
export const metadata = {
  title: "Blog App",
  description: "Generated by me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>

        <nav className="flex">
          <ul className=" ">
            <li><Link href='/'>Home</Link></li>
            <li><Link href='/about'>About</Link></li>
            <li><Link href='/blog'>Blog</Link></li>
            <li><Link href='/posts'>posts</Link></li>
          </ul>
        </nav>
        {children}

      </body>
    </html>
  );
}
